### ISSUE TITLE
Blocked Orders stay in canceling state and dont go away

### ISSUE THREAD

**Issue by rfx77** [sos-berlin/js7#11]
Hi!

I have a defunct agent which i dont want to use again and want to delete. All workflows of this Agent are blocked. i removed all workflow definitions and daily-plan entries and canceled the orders but the dont go away. How can i get rid of this orders.

i am on 2.6.5

![image](https://github.com/sos-berlin/js7/assets/61699304/00973860-0b6f-46a9-b5cb-810b27283d41)

**Comment by sosap** [comment]
Please consider [https://kb.sos-berlin.com/display/JS7/JS7+-+How+to+remove+an+Agent+or+an+Order+from+the+Journal](https://kb.sos-berlin.com/display/JS7/JS7+-+How+to+remove+an+Agent+or+an+Order+from+the+Journal) which allows to remove an Agent from the Controller's journal and to put related oders to the _failed_ state from which they can be cancelled.

**Comment by rfx77** [comment]
After using this procedure to remove a workflow and an agent the controller is always dead with this error:

`./update-journal.sh --controller-id=jobscheduler --journal-dir=/var/lib/docker/volumes/js7_controller/_data/state/ --controller --workflow=Updates.Nextcloud  --remove
`
`./update-journal.sh --controller-id=jobscheduler --journal-dir=/var/lib/docker/volumes/js7_controller/_data/state/ --controller --agent-id=svkdt43 --remove`


The controller is stopped while doing this.


```
2024-08-12T07:30:16,780 info  js7.journal.recover.StateRecoverer - Recovering from file controller--1723447562706005.journal (294kB)
2024-08-12T07:30:16,936 info  js7.base.crypt.generic.DirectoryWatchingSignatureVerifier - Trusting signature key
2024-08-12T07:30:16,948 info  js7.base.crypt.generic.DirectoryWatchingSignatureVerifier -   X.509 origin=/var/sos-berlin.com/js7/controller/config/private/trusted-x509-keys
2024-08-12T07:30:16,948 info  js7.base.crypt.generic.DirectoryWatchingSignatureVerifier -     X.509 certificate EMAILADDRESS=admin@sos-berlin.com, CN=SOS Intermediate CA, OU=IT, O=SOS, L=Berlin, ST=Berlin, C=DE · CA, fingerprint=d2689951 4827d60c 503001b8 0dc75024 e57b7de8 keyUsage=digitalSignature,keyCertSign,crlSign
2024-08-12T07:30:17,904 ERROR js7.common.system.startup.JavaMain - Application of snapshot object 'VersionedEvent.VersionedItemRemoved' failed in record #157 for ControllerState, caused by: UnknownKey: No such VersionedItemPath: Workflow:Updates.Nextcloud
java.lang.RuntimeException: Application of snapshot object 'VersionedEvent.VersionedItemRemoved' failed in record #157 for ControllerState
        at js7.data.event.SnapshotableStateBuilder.addSnapshotObject(SnapshotableStateBuilder.scala:81) ~[com.sos-berlin.js7.engine.js7-engine-2.6.5.jar:2.6.5]
        at js7.data.event.SnapshotableStateBuilder.addSnapshotObject$(SnapshotableStateBuilder.scala:56) ~[com.sos-berlin.js7.engine.js7-engine-2.6.5.jar:2.6.5]
        at js7.data.controller.ControllerStateBuilder.addSnapshotObject(ControllerStateBuilder.scala:34) ~[com.sos-berlin.js7.engine.js7-engine-2.6.5.jar:2.6.5]
        at js7.journal.recover.FileSnapshotableStateBuilder.put(FileSnapshotableStateBuilder.scala:91) ~[com.sos-berlin.js7.engine.js7-engine-2.6.5.jar:2.6.5]
        at js7.journal.recover.StateRecoverer.$anonfun$recoverAll$4(StateRecoverer.scala:39) ~[com.sos-berlin.js7.engine.js7-engine-2.6.5.jar:2.6.5]
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:576) ~[org.scala-lang.scala-library-2.13.11.jar:?]
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:574) ~[org.scala-lang.scala-library-2.13.11.jar:?]
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1300) ~[org.scala-lang.scala-library-2.13.11.jar:?]
        at js7.journal.recover.StateRecoverer.$anonfun$recoverAll$1(StateRecoverer.scala:38) ~[com.sos-berlin.js7.engine.js7-engine-2.6.5.jar:2.6.5]
        at js7.journal.recover.StateRecoverer.$anonfun$recoverAll$1$adapted(StateRecoverer.scala:37) ~[com.sos-berlin.js7.engine.js7-engine-2.6.5.jar:2.6.5]
        at js7.base.utils.AutoClosing$.$anonfun$autoClosing$1(AutoClosing.scala:22) ~[com.sos-berlin.js7.engine.js7-engine-2.6.5.jar:2.6.5]
        at js7.base.utils.AutoClosing$.closeOnError(AutoClosing.scala:30) ~[com.sos-berlin.js7.engine.js7-engine-2.6.5.jar:2.6.5]
        at js7.base.utils.AutoClosing$.autoClosing(AutoClosing.scala:22) ~[com.sos-berlin.js7.engine.js7-engine-2.6.5.jar:2.6.5]
        at js7.journal.recover.StateRecoverer.recoverAll(StateRecoverer.scala:37) ~[com.sos-berlin.js7.engine.js7-engine-2.6.5.jar:2.6.5]
        at js7.journal.recover.StateRecoverer$.recover(StateRecoverer.scala:90) ~[com.sos-berlin.js7.engine.js7-engine-2.6.5.jar:2.6.5]
        at js7.journal.recover.StateRecoverer$.$anonfun$resource$1(StateRecoverer.scala:74) ~[com.sos-berlin.js7.engine.js7-engine-2.6.5.jar:2.6.5]
        at make @ js7.base.thread.IOExecutor$.resource(IOExecutor.scala:65) ~[?:?]
        at make @ js7.base.thread.IOExecutor$.resource(IOExecutor.scala:65) ~[?:?]
        at allocated @ js7.base.monixutils.MonixBase$syntax$RichMonixResource$.executeOn$extension(MonixBase.scala:349) ~[?:?]
        at flatMap @ js7.base.service.Service.startService(Service.scala:69) ~[?:?]
        at as @ js7.base.service.Service.startService(Service.scala:74) ~[?:?]
        at flatTap @ js7.base.service.Service$.resource(Service.scala:92) ~[?:?]
        at make @ js7.base.thread.IOExecutor$.resource(IOExecutor.scala:65) ~[?:?]
        at make @ js7.base.thread.IOExecutor$.resource(IOExecutor.scala:65) ~[?:?]
        at allocated @ js7.base.monixutils.MonixBase$syntax$RichMonixResource$.executeOn$extension(MonixBase.scala:349) ~[?:?]
        at make @ js7.base.thread.IOExecutor$.resource(IOExecutor.scala:65) ~[?:?]
        at ________________________________________.________________________________________(appended) ~[?:?]
        at js7.base.thread.MonixBlocking$syntax$RichTask$.await$extension(MonixBlocking.scala:34) ~[com.sos-berlin.js7.engine.js7-engine-2.6.5.jar:2.6.5]
        at js7.base.thread.MonixBlocking$syntax$RichTask$.awaitInfinite$extension(MonixBlocki
```
