### ISSUE TITLE
YADE transfer error when WebDAV file has space characters

### ISSUE THREAD

**Issue by rfx77** [sos-berlin/js7#5]
When i configure a WebDAV Filetransfer in JS7 i get an Error when the remote file has a space-character in it.

This is the Exception:
`2023-07-18T15:12:22,619 ERROR main c.s.D.SOSDataExchangeEngineMain - execute: Error occurred ...: SOSVfs_E_173: read failed for file /DRIVE/FLASH/ansagen/2_Text zur Zeit nicht erreichbar.g711a (SOSVfs_E_158: getFileInputStream() failed in /DRIVE/FLASH/ansagen/2_Text zur Zeit nicht erreichbar.g711a (SOSVfs_E_193: 'getInputStream()' failed ['/DRIVE/FLASH/ansagen/2_Text zur Zeit nicht erreichbar.g711a'] (Illegal character in path at index 27: /DRIVE/FLASH/ansagen/2_Text zur Zeit nicht erreichbar.g711a))), exit-code 99 raised
com.sos.JSHelper.Exceptions.JobSchedulerException: SOSVfs_E_173: read failed for file /DRIVE/FLASH/ansagen/2_Text zur Zeit nicht erreichbar.g711a (SOSVfs_E_158: getFileInputStream() failed in /DRIVE/FLASH/ansagen/2_Text zur Zeit nicht erreichbar.g711a (SOSVfs_E_193: 'getInputStream()' failed ['/DRIVE/FLASH/ansagen/2_Text zur Zeit nicht erreichbar.g711a'] (Illegal character in path at index 27: /DRIVE/FLASH/ansagen/2_Text zur Zeit nicht erreichbar.g711a)))
	at com.sos.vfs.webdav.jackrabbit.SOSWebDAVFile.read(SOSWebDAVFile.java:37) ~[com.sos-berlin.jobscheduler.virtual-file-system-1.13.18.jar:1.13.18]
	at com.sos.vfs.common.SOSFileListEntry.doTransfer(SOSFileListEntry.java:227) ~[com.sos-berlin.jobscheduler.virtual-file-system-1.13.18.jar:1.13.18]
	at com.sos.vfs.common.SOSFileListEntry.run(SOSFileListEntry.java:1208) ~[com.sos-berlin.jobscheduler.virtual-file-system-1.13.18.jar:1.13.18]
	at com.sos.DataExchange.SOSDataExchangeEngine.sendFiles(SOSDataExchangeEngine.java:1076) ~[com.sos-berlin.jade.jade-engine-1.13.18.jar:1.13.18]
	at com.sos.DataExchange.SOSDataExchangeEngine.transfer(SOSDataExchangeEngine.java:1358) ~[com.sos-berlin.jade.jade-engine-1.13.18.jar:1.13.18]
	at com.sos.DataExchange.SOSDataExchangeEngine.execute(SOSDataExchangeEngine.java:430) ~[com.sos-berlin.jade.jade-engine-1.13.18.jar:1.13.18]
	at com.sos.DataExchange.SOSDataExchangeEngineMain.execute(SOSDataExchangeEngineMain.java:76) [com.sos-berlin.jade.jade-engine-1.13.18.jar:1.13.18]
	at com.sos.DataExchange.SOSDataExchangeEngineMain.main(SOSDataExchangeEngineMain.java:58) [com.sos-berlin.jade.jade-engine-1.13.18.jar:1.13.18]
Caused by: com.sos.JSHelper.Exceptions.JobSchedulerException: SOSVfs_E_158: getFileInputStream() failed in /DRIVE/FLASH/ansagen/2_Text zur Zeit nicht erreichbar.g711a (SOSVfs_E_193: 'getInputStream()' failed ['/DRIVE/FLASH/ansagen/2_Text zur Zeit nicht erreichbar.g711a'] (Illegal character in path at index 27: /DRIVE/FLASH/ansagen/2_Text zur Zeit nicht erreichbar.g711a))
	at com.sos.vfs.common.SOSCommonProviderFile.getFileInputStream(SOSCommonProviderFile.java:63) ~[com.sos-berlin.jobscheduler.virtual-file-system-1.13.18.jar:1.13.18]
	at com.sos.vfs.webdav.jackrabbit.SOSWebDAVFile.read(SOSWebDAVFile.java:31) ~[com.sos-berlin.jobscheduler.virtual-file-system-1.13.18.jar:1.13.18]
	... 7 more
Caused by: com.sos.JSHelper.Exceptions.JobSchedulerException: SOSVfs_E_193: 'getInputStream()' failed ['/DRIVE/FLASH/ansagen/2_Text zur Zeit nicht erreichbar.g711a'] (Illegal character in path at index 27: /DRIVE/FLASH/ansagen/2_Text zur Zeit nicht erreichbar.g711a)
	at com.sos.vfs.webdav.jackrabbit.SOSWebDAV.getInputStream(SOSWebDAV.java:392) ~[com.sos-berlin.jobscheduler.virtual-file-system-1.13.18.jar:1.13.18]
	at com.sos.vfs.common.SOSCommonProviderFile.getFileInputStream(SOSCommonProviderFile.java:60) ~[com.sos-berlin.jobscheduler.virtual-file-system-1.13.18.jar:1.13.18]
	at com.sos.vfs.webdav.jackrabbit.SOSWebDAVFile.read(SOSWebDAVFile.java:31) ~[com.sos-berlin.jobscheduler.virtual-file-system-1.13.18.jar:1.13.18]
	... 7 more
Caused by: java.net.URISyntaxException: Illegal character in path at index 27: /DRIVE/FLASH/ansagen/2_Text zur Zeit nicht erreichbar.g711a
	at java.net.URI$Parser.fail(URI.java:2976) ~[?:?]
	at java.net.URI$Parser.checkChars(URI.java:3147) ~[?:?]
	at java.net.URI$Parser.parseHierarchical(URI.java:3229) ~[?:?]
	at java.net.URI$Parser.parse(URI.java:3188) ~[?:?]
	at java.net.URI.<init>(URI.java:623) ~[?:?]
	at com.sos.vfs.http.common.SOSHTTPClient.normalizeURI(SOSHTTPClient.java:236) ~[com.sos-berlin.jobscheduler.virtual-file-system-1.13.18.jar:1.13.18]
	at com.sos.vfs.webdav.jackrabbit.SOSWebDAV.getInputStream(SOSWebDAV.java:371) ~[com.sos-berlin.jobscheduler.virtual-file-system-1.13.18.jar:1.13.18]
	at com.sos.vfs.common.SOSCommonProviderFile.getFileInputStream(SOSCommonProviderFile.java:60) ~[com.sos-berlin.jobscheduler.virtual-file-system-1.13.18.jar:1.13.18]
	at com.sos.vfs.webdav.jackrabbit.SOSWebDAVFile.read(SOSWebDAVFile.java:31) ~[com.sos-berlin.jobscheduler.virtual-file-system-1.13.18.jar:1.13.18]
	... 7 more`

**Comment by sosap** [comment]
Thank you. The issue is confirmed and has been added to our change management system:

- [YADE-605: YADE transfer throws the error with WebDAV protocol when source file name contains space](https://change.sos-berlin.com/browse/YADE-605)

The fix will become available with [Release 1.13.20](https://kb.sos-berlin.com/x/04jqBg).
