### ISSUE TITLE
Cannot change job_resource in MailFragment of the notification configuration

### ISSUE THREAD

**Issue by rfx77** [sos-berlin/js7#7]
When i try to select the job_resource in a MailFragment of the notification config, this is not possible.
There is a javascript error in the console but it is obfuscated:

main.56ca4128749d4bdb.js?v=1687872249526:1 TypeError: this.list[this.attribute].splice is not a function
    at E.onSelect (26420.e7843fd64fd85e44.js:1:112790)
    at 26420.e7843fd64fd85e44.js:1:111889
    at Pp (main.56ca4128749d4bdb.js?v=1687872249526:1:1406451)
    at Object.T [as next] (main.56ca4128749d4bdb.js?v=1687872249526:1:1406590)
    at R.next (main.56ca4128749d4bdb.js?v=1687872249526:1:1113174)
    at I._next (main.56ca4128749d4bdb.js?v=1687872249526:1:1112858)
    at I.next (main.56ca4128749d4bdb.js?v=1687872249526:1:1112553)
    at main.56ca4128749d4bdb.js?v=1687872249526:1:1110511
    at a (main.56ca4128749d4bdb.js?v=1687872249526:1:1137824)
    at ab.next (main.56ca4128749d4bdb.js?v=1687872249526:1:1110350)

i am on version 2.6.0

**Comment by sosap** [comment]
Thank you. We are aware of the issue that is fixed for the upcoming 2.5.4 and 2.6.1 releases (available next week).

**Comment by sosap** [comment]
This issue is fixed with release [2.5.4](https://kb.sos-berlin.com/x/THOwBQ) and [2.6.1](https://kb.sos-berlin.com/x/hAy3Bg) respectively.
